version: "2"

services:

  collector:
    container_name: collector
    build: ./collector
    image: collector:0.0.1
    env_file: .env
    ports:
      - 8080:80
    depends_on:
      - zookeeper
      - kafka
    volumes:
      - ./logs/collector:/logs
    tty: true
    networks:
      neons:
        ipv4_address: 10.0.0.10

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    env_file: .env
    ports:
      - 2181:2181
    networks:
      neons:
        ipv4_address: 10.0.0.11

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    env_file: .env
    ports:
      - 9092:9092
      - 9999:9999
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      neons:
        ipv4_address: 10.0.0.12

networks:
  neons:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.0.0/24
