version: "3"

services:

  collector:
    container_name: collector
    build: ./collector
    image: collector:0.0.1
    env_file: .env
    ports:
      - 8080:80
    depends_on:
      - redis
    volumes:
      - ./logs/collector:/logs
    tty: true
    networks:
      neons:
        ipv4_address: 10.0.0.10

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    networks:
      neons:
        ipv4_address: 10.0.0.11

networks:
  neons:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.0.0/24
